list.Add("NPCUsableWeapons", {class = "Weapon_ace_ak74m", title = "[ACE+] AK-74M"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_ak47mod", title = "[ACE+] AK-47"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_ak74u", title = "[ACE+] AK-74U"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_an94", title = "[ACE+] AN-94"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_asval", title = "[ACE+] AS VAL"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_auga1", title = "[ACE+] AUG A1"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_dbshotgun", title = "[ACE+] double barrel shotgun"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_famasmod", title = "[ACE+] Famas"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_fnfal", title = "[ACE+] FN FAL"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_g3", title = "[ACE+] G3"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_g23", title = "[ACE+] Glock 23"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_g36c", title = "[ACE+] G36C"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_g36e", title = "[ACE+] G36E"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_k1", title = "[ACE+] K1"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_k2", title = "[ACE+] K2"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_k7", title = "[ACE+] K7"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_l85", title = "[ACE+] L85"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_l85mod", title = "[ACE+] L85 Mod"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_m4a1", title = "[ACE+] M4A1"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_m14", title = "[ACE+] M14"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_m16a3", title = "[ACE+] M16A3"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_m32gl", title = "[ACE+] M32 GL"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_m60", title = "[ACE+] M60"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_m72law", title = "[ACE+] M72 LAW"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_m92fs", title = "[ACE+] M92FS"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_m200", title = "[ACE+] M200"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_m416", title = "[ACE+] M416"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_makarov", title = "[ACE+] PM (makarov)"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_matador", title = "[ACE+] RGW 90 MATADOR"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_mg36", title = "[ACE+] MG36"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_panzerfaust3", title = "[ACE+] PanzerFaust 3"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_pkm", title = "[ACE+] PKM"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_pp19", title = "[ACE+] PP 19"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_r870", title = "[ACE+] R870"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_rpg7", title = "[ACE+] RPG 7"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_rpg7v2", title = "[ACE+] RPG 7V2"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_rpg7v2t", title = "[ACE+] RPG 7V2 tandem"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_rpg26", title = "[ACE+] RPG 26"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_rpg28", title = "[ACE+] RPG 28"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_rpk", title = "[ACE+] RPK"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_rpk74", title = "[ACE+] RPK 74"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_saiga", title = "[ACE+] Saiga 12k"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_scarl", title = "[ACE+] SCAR L"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_scarh", title = "[ACE+] SCAR H"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_sg550", title = "[ACE+] SG550"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_spas12", title = "[ACE+] SPAS 12"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_sv98", title = "[ACE+] SV 98"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_svd", title = "[ACE+] SVD"})
list.Add("NPCUsableWeapons", {class = "Weapon_ace_ump", title = "[ACE+] UMP 45"})
